### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by glennjacobs** [fuel/orm#33] opened 2011-05-20 22:02 UTC
Memory gradually increases as I used related entries.

If I do a query such as
$queue = \Model_Queue::find()->related('keyword')->get();

And then loop using

foreach ($queue as $entry)
{
    $keyword = $entry->keyword->keyword;
    unset($entry);
}

Memory gradually increases...

If I comment out 
//$keyword = $entry->keyword->keyword;

Then memory remains constant.

I'm trying to see what might be causing it, but might be better for the developer to have a look?

**Comment by jschreuder** [comment] 2011-05-20 22:03
I think you're lazy loading stuff, anyway I can't tell from this so I'm closing this and marking it invalid. If you have anything to prove there's a "memory leak" produce it and I'll take a second look.

**Closed as completed by jschreuder** 2011-05-20 22:03 UTC
Labels: Invalid

**Comment by glennjacobs** [comment] 2011-05-20 22:06
I hit enter by mistake... I edited the comment to include my findings.

If it's not a 'bug', then it would be good to understand how best to tidy up to stop the memory increasing. Thanks

**Comment by jschreuder** [comment] 2011-05-20 22:10
Judging by this it looks like you're lazy loading them as I speculated, though if your code is really exactly like this that shouldn't happen. But the only way I could tell is if I knew for sure more queries are executed. You need to investigate this a little further yourself, because I can't tell from this and I haven't experienced something similar yet.

**Comment by glennjacobs** [comment] 2011-05-20 22:11
Here's a code snippet that might help

$queue = \Model_Queue::find()->related('keyword')->get();

foreach ($queue as $entry)
{

```
$keyword = $entry->keyword->keyword;

unset($entry);

\Cli::write("Memory: " . memory_get_usage());
```

}

As said, if it's not a 'bug', then it would be good to understand how best to tidy up to stop the memory increasing. Thanks

**Comment by jschreuder** [comment] 2011-05-20 22:37
It's a very small "memory-leak", about a 150 bytes per requested property (what I'm saying is that it's not a memory leak). The cause is that we use the `__get()` magic method in the models and PHP isn't very good at magic methods.

I tested it with [this code](http://scrp.at/Z7) which gave me [this output](http://scrp.at/Z8) - as you can see the test object is actually worse than the Orm\Model instance (I must admit I don't get that btw).

**Comment by glennjacobs** [comment] 2011-05-20 22:45
I know, it's very small and for normal web usage it really wouldn't cause any concern. It's just I'm running through a big data set and was having trouble with something else (libxml) eating up memory, I fixed that but then noticed this.

The script will be running for a fair while using Oil, so I wanted to stop any memory increase in the cycle if possible.

Thanks for letting me know.

**Comment by jschreuder** [comment] 2011-05-20 22:47
When handling massive datasets you're probably better off using just the query builder, the Orm adds overhead which is negligable when just editing some stuff or listing a paginated page. But when you go massive the overhead will be noticeable, an Orm isn't meant to deal with that stuff because that needs specific optimizations while an Orm offers a general convention.

**Comment by glennjacobs** [comment] 2011-05-20 22:50
I was thinking the same thing, I was using the ORM package purely to have a play ;-)

It is very nice by the way!
