### ISSUE TITLE
Model_Temporal and Eager Loading

### ISSUE THREAD

**Issue by kaorun343** [fuel/orm#351] opened 2014-06-06 18:56 UTC
This issue might be similar to #347.

I made two models: "Model_Customer_Info", which inherits from a normal ORM Model, and "Model_Customer_Lecture", which inherits from "Model_Temporal."

Here is the relations between these two Models.

``` php
// Model_Customer_Info extends \Orm\Model
// Model_Customer_Info has a property named "lectue_id."
protected static $_belongs_to = array(
    'lecture' => array(
        'key_from' => 'lecture_id',
        'model_to' => 'Model_Customer_Lecture',
        'key_to' => 'id',
        'cascade_save' => true,
        'cascade_delete' => false,
  ),
);

// Model_Customer_Lecture extends \Orm\Model_Temporal
protected static $_has_one = array(
    'info' => array(
        'key_from' => 'id',
        'model_to' => 'Model_Customer_Info',
        'key_to' => 'lecture_id',
        'cascade_save' => true,
        'cascade_delete' => false,
  ),
);
```

What I'd like to do is here.

``` php
$data = Model_Customer_Info::find($id, ['related' => ['lecture']]);
```

and get the newest revision of lecture. However, 

``` php
var_dump($data->lecture);
```

always returns the first one despite that there're several revisions.

Is there the correct way to do so?

**Comment by emlynwest** [comment] 2014-06-06 19:01
Does the relation load correctly via lazy loading? If so this is an exact duplicate of #347

**Comment by kaorun343** [comment] 2014-06-06 20:01
No, correctly via eager loading.

**Comment by emlynwest** [comment] 2014-06-06 20:22
What version of fuel are you using? If you are using 1.7 then try the latest 1.8/develop.

**Comment by kaorun343** [comment] 2014-06-06 20:30
I'm using 1.8 (d841283), the latest version of orm.

**Comment by emlynwest** [comment] 2014-06-06 20:37
Ok thanks

**Comment by WanWizard** [comment] 2015-02-15 12:10
I checked the different relation objects. They all use the query() method of the Model_To object to construct the related get(), so lazy loading should not be a problem at all.

Eager loading doesn't work is because the standard Query object to construct the query, and that is not away of the temporal model. Fixing this requires a complete ORM redesign.

**Closed as completed by WanWizard** 2015-02-15 12:10 UTC
