### ISSUE TITLE
count() doesn't take joined tables in account

### ISSUE THREAD

**Issue by krtek4** [fuel/orm#76] opened 2011-08-28 06:05 UTC
Say I have `accounts` and `pictures`. `accounts` is linked by a "has many" relationship to `pictures`, which is in return linked to `accounts` with a "belongs to" relationship. The following code :

```
 Model_Account->find()->related('pictures')->where('pictures.account_id', '!=', null)->count();
```

should return only the number of account which have at least one picture, but the total number of accounts is returned.

**Comment by jschreuder** [comment] 2011-08-28 13:43
`count()` queries don't take relations into account by design, they only count the base table. Your query description isn't correct btw, you wouldn't be counting the number of accounts with at least one picture but you'd be counting the pictures that are assigned to an account. If one or more accounts have multiple pictures it wouldn't be the output you described.

It's a limitation that is logical for one->many or many->many for this very reason, but one->one would actually be nice to be able to do this - however that isn't easy to do while still ignoring the many relations.

**Closed as completed by jschreuder** 2011-08-28 13:43 UTC
Labels: Invalid

**Comment by krtek4** [comment] 2011-08-28 15:09
Thanks for the answer !

You're right about the result of the count... In my particular design the account has either one or no picture, reason for my mistake...

Isn't it possible to add another count() method ? Otherwise, what will be the best way to get the right result, knowing that certain other condition where condition can be applied  ?

For the time being, I'll stick with my custom SQL query :)

**Comment by jschreuder** [comment] 2011-08-28 15:13
Actually in cases like this I doubt there's a better way than a custom SQL query. An Orm needs a logical interface that does all common tasks, but it's impossible to implement the full power of SQL while still keeping a clean interface (unless you take the DQL route of Doctrine, but that won't happen for our Orm). Some things will be revisited down the line and possibly a bit more flexibility added, but this isn't anywhere on my radar right now so I won't promise anything.
